[package]
name = "nes"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "s"
strip = "symbols"
panic = "abort"
lto = true
codegen-units = 1

[dependencies]
anyhow = "1.0.58"
bitflags = "1.3.2"

[dev-dependencies]
regex = "1.5.6"
