version: '3'
services:
  nes-emu:
    image: melvinsamxd/nes-emu:v1
    container_name: c-nes-emu
    restart: always
    build:
      context: ../../../
      dockerfile: web/Dockerfile
    ports:
      - 8002:8000
    networks:
      - nes-emu
networks:
  nes-emu: